apiVersion: database.oracle.com/v1alpha1
kind: CDB
metadata:
  name: 23aicdb
  namespace: 23aidemo
spec:
  cdbAdminPwd:
    secret:
      key: cdbadmin_pwd
      secretName: 23aicdb-secret
  cdbAdminUser:
    secret:
      key: cdbadmin_user
      secretName: 23aicdb-secret
  cdbName: DB19c
  cdbTlsCrt:
    secret:
      key: tls.crt
      secretName: db-tls
  cdbTlsKey:
    secret:
      key: tls.key
      secretName: db-tls
  dbPort: 1521
  dbServer: db23ai.23aidemo
  ordsImage: fra.ocir.io/frul1g8cgfam/pub_ordsrestmgmt:23.1
  ordsImagePullPolicy: Always
  ordsPort: 8888
  ordsPwd:
    secret:
      key: ords_pwd
      secretName: 23aicdb-secret
  replicas: 1
  serviceName: DB19c_fra1gq.publicdevnet.k8snet.oraclevcn.com
  sysAdminPwd:
    secret:
      key: sysadmin_pwd
      secretName: 23aicdb-secret
  webServerPwd:
    secret:
      key: webserver_pwd
      secretName: 23aicdb-secret
  webServerUser:
    secret:
      key: webserver_user
      secretName: 23aicdb-secret
