apiVersion: database.oracle.com/v1alpha1
kind: CDB
metadata:
  name: ai23-cloud-cdb
  namespace: 23aidemo
spec:
  cdbAdminPwd:
    secret:
      key: cdbadmin_pwd
      secretName: aicdb-secret
  cdbAdminUser:
    secret:
      key: cdbadmin_user
      secretName: aicdb-secret
  cdbName: DB23ai
  cdbTlsCrt:
    secret:
      key: tls.crt
      secretName: db-tls
  cdbTlsKey:
    secret:
      key: tls.key
      secretName: db-tls
  dbPort: 1521
  dbServer: db23ai.privatek8snet.k8snet.oraclevcn.com
  ordsImage: fra.ocir.io/frul1g8cgfam/pub_ordsrestmgmt:23.4
  ordsImagePullPolicy: Always
  ordsPort: 8888
  ordsPwd:
    secret:
      key: ords_pwd
      secretName: aicdb-secret
  replicas: 1
  serviceName: DB23ai_xbc_fra.privatek8snet.k8snet.oraclevcn.com
  sysAdminPwd:
    secret:
      key: sysadmin_pwd
      secretName: aicdb-secret
  webServerPwd:
    secret:
      key: webserver_pwd
      secretName: aicdb-secret
  webServerUser:
    secret:
      key: webserver_user
      secretName: aicdb-secret
