apiVersion: v1
kind: ConfigMap
metadata:
  name: ords-init-config
  namespace: sidb23c
data:
  ordssetup.sh: |-
    #!/bin/bash
    ords install --admin-user $ADMIN_USER --proxy-user --db-hostname $DB_HOST --db-port $DB_PORT --db-servicename $DB_SERVICENAME --feature-sdw true --password-stdin <<EOF
    $ADMIN_PWD
    $PROXY_PWD
    EOF
    cd /etc/ords/config
    curl -o apex.zip https://download.oracle.com/otn_software/apex/apex-latest.zip
    jar xvf apex.zip
    rm apex.zip
    chmod -R 755 apex
    ords config set standalone.static.path /etc/ords/config/apex/images
