apiVersion: apps/v1
kind: Deployment
metadata:
  name: ords-nondev-sidb23c
  namespace: sidb23c
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ords-nondev-sidb23c
      app.kubernetes.io/name: ords-nondev
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ords-nondev-sidb23c
        app.kubernetes.io/name: ords-nondev
    spec:
      initContainers:
      - name: set-config
        env:
        - name: ADMIN_USER
          valueFrom:
             secretKeyRef:
                key: admin_user
                name: ords-secret
        - name: ADMIN_PWD
          valueFrom:
             secretKeyRef:
                key: admin_pwd
                name: ords-secret
        - name: PROXY_PWD
          valueFrom:
             secretKeyRef:
                key: proxy_pwd
                name: ords-secret
        - name: DB_HOST
          valueFrom:
             secretKeyRef:
                key: db_host
                name: ords-secret
        - name: DB_PORT
          valueFrom:
             secretKeyRef:
                key: db_port
                name: ords-secret
        - name: DB_SERVICENAME
          valueFrom:
             secretKeyRef:
                key: db_servicename
                name: ords-secret
        command:
          - /bin/bash
          - /scripts/ords_setup.sh
        image: container-registry.oracle.com/database/ords:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /scripts
          name: scripts
        - mountPath: /etc/ords/config
          name: config
      containers:
      - image: container-registry.oracle.com/database/ords:latest
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8181
          name: http-ords
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/ords/config
          name: config
      volumes:
      - name: scripts
        configMap:
          defaultMode: 420
          name: ords-init-config
      - name: config
        emptyDir: {}

