apiVersion: apps/v1
kind: Deployment
metadata:
  name: ords-sidb23c
  namespace: sidb23c
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ords-sidb23c
      app.kubernetes.io/name: ords
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ords-sidb23c
        app.kubernetes.io/name: ords
    spec:
      containers:
      - image: 'fra.ocir.io/frul1g8cgfam/pub_ords:24.3.0-graal'	
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8181
          name: https-ords
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/oracle/variables
          name: secretords
      volumes:
      - name: secretords
        secret:
          defaultMode: 420
          secretName: ords-secret
