apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  labels:
  name: aipdb-prepare-job
  namespace: 23aidemo
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: aipdb-prepare-job
    spec:
      restartPolicy: Never
      #restartPolicy: OnFailure
      containers:
        - command:
            - /bin/bash
            - /scripts/prepare.sh
          env:
            - name: DB_HOST
#              value: db23ai.23aidemo
              value: db23ai.privatek8snet.k8snet.oraclevcn.com
            - name: DB_SERVICE
#              value: AIPDB
              value: remoteaipdb.privatek8snet.k8snet.oraclevcn.com
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: oracle_pwd
                  name: db-admin-secret
          image: 'fra.ocir.io/frul1g8cgfam/database/aidemo:23.4'
          imagePullPolicy: IfNotPresent
          name: dbhelper
          volumeMounts:
            - mountPath: /scripts
              name: scripts
      initContainers:
        - command:
            - /bin/bash
            - /scripts/testconn.sh
          env:
            - name: DB_HOST
#              value: db23ai.23aidemo
              value: db23ai.privatek8snet.k8snet.oraclevcn.com
            - name: DB_SERVICE
#              value: AIPDB
              value: remoteaipdb.privatek8snet.k8snet.oraclevcn.com
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: oracle_pwd
                  name: db-admin-secret
          image: 'fra.ocir.io/frul1g8cgfam/database/aidemo:23.4'
          imagePullPolicy: IfNotPresent
          name: dbcheck
          volumeMounts:
            - mountPath: /scripts
              name: scripts
      volumes:
        - configMap:
            defaultMode: 420
            name: aipdb-prepare-config
          name: scripts
