apiVersion: v1
kind: ConfigMap
metadata:
  name: aipdb-prepare-config
  namespace: 23aidemo
data:
  prepare.sh: |-
    #!/bin/bash 
    curl https://raw.githubusercontent.com/ilfur/OraOperatorDBWithApp/sidbpluscdb/dbscripts/01_embedding/01_create_user_vector.sql -o /opt/vecdump/01_create_user_vector.sql
    cd /opt/vecdump
    sqlplus sys/$DB_PASSWORD@$DB_HOST:1521/$DB_SERVICE as sysdba << EOF 
    @01_create_user_vector.sql
    exit; 
    EOF 
  testconn.sh: |-
    #!/bin/bash 
     sqlplus sys/$DB_PASSWORD@$DB_HOST:1521/$DB_SERVICE as sysdba << EOF 
     whenever sqlerror exit failure; 
     select * from dual; 
     exit; 
     EOF 
     if [ $? -eq 0 ] ; then echo "connect successful" ; else echo "DB connect failed, waiting 3 min and exiting..." ; sleep 180 ; exit 5 ; fi 
