apiVersion: v1
data:
  prepare.sh: |-
    #!/bin/bash 
     sqlplus / AS SYSDBA << EOF 
     ALTER USER SYS IDENTIFIED BY "$DB_PASSWORD"; 
     ALTER USER SYSTEM IDENTIFIED BY "$DB_PASSWORD"; 
     ALTER SESSION SET CONTAINER=ORCLPDB1; 
     ALTER USER PDBADMIN IDENTIFIED BY "$DB_PASSWORD"; 
     exit; 
     EOF 
  testconn.sh: |-
    /opt/oracle/sqlcl/bin/sql /nolog << EOF 
     whenever sqlerror exit failure; 
     connect sys/$DB_PASSWORD@dbai23c.aidemo:1521/$DB_SERVICE as sysdba 
     select * from dual; 
     exit; 
     EOF 
     if [ $? -eq 0 ] ; then echo "connect successful" ; else echo "DB connect failed, waiting 2 mins and exiting..." ; sleep 120 ; exit 5 ; fi 
