apiVersion: v1
kind: ConfigMap
metadata:
  name: aidb23cdb-prepare-config
  namespace: 23aidemo
data:
  prepare.sh: |-
    #!/bin/bash 
     sqlplus sys/$DB_PASSWORD@$DB_HOST:1521/$DB_SERVICE as sysdba << EOF 
     ALTER SESSION SET "_oracle_script"=true;
     DROP USER  $CDBADMIN_USER cascade;
     CREATE USER $CDBADMIN_USER IDENTIFIED BY $CDBADMIN_PWD CONTAINER=ALL ACCOUNT UNLOCK;
     GRANT SYSOPER TO $CDBADMIN_USER CONTAINER = ALL;
     GRANT SYSDBA TO $CDBADMIN_USER CONTAINER = ALL;
     GRANT CREATE SESSION TO $CDBADMIN_USER CONTAINER = ALL;
     DROP USER ORDS_METADATA CASCADE;
     DROP USER ORDS_PUBLIC_USER CASCADE;
     DROP ROLE ORDS_ADMINISTRATOR_ROLE;
     DROP ROLE ORDS_RUNTIME_ROLE;
     ALTER PLUGGABLE DATABASE PDB\$SEED CLOSE;
     ALTER PLUGGABLE DATABASE PDB\$SEED OPEN READ WRITE;
     ALTER SESSION SET CONTAINER=PDB\$SEED;
     DROP USER ORDS_METADATA CASCADE;
     DROP USER ORDS_PUBLIC_USER CASCADE;
     DROP ROLE ORDS_ADMINISTRATOR_ROLE;
     DROP ROLE ORDS_RUNTIME_ROLE;
     ALTER SESSION SET CONTAINER=CDB\$ROOT;
     exit; 
     EOF 
  testconn.sh: |-
    #!/bin/bash 
     sqlplus sys/$DB_PASSWORD@$DB_HOST:1521/$DB_SERVICE as sysdba << EOF 
     whenever sqlerror exit failure; 
     select * from dual; 
     exit; 
     EOF 
     if [ $? -eq 0 ] ; then echo "connect successful" ; else echo "DB connect failed, waiting 2 mins and exiting..." ; sleep 120 ; exit 5 ; fi 
