apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: instantclient
    app.kubernetes.io/name: instantclient-sqlplus
  name: instantclient-sqlplus
  namespace: 23aidemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: instantclient
      app.kubernetes.io/name: instantclient-sqlplus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: instantclient
        app.kubernetes.io/name: instantclient-sqlplus
    spec:
      containers:
      - name: app
        env:
        - name: ORAPWD
          value: orapwd
        image: docker.io/ilfur/sqlcl-liquibase:21.3.0.0.0
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
          name: console
          protocol: TCP
        volumeMounts:
        - mountPath: /projects
          name: storage
      initContainers:
      - name: getFiles
        command:
          - /bin/bash
          - /scripts/getfiles.sh
        image: 'docker.io/busybox:latest'
        imagePullPolicy: IfNotPresent
        name: getfiles
        volumeMounts:
        - mountPath: /scripts
          name: scripts
        - mountPath: /projects
          name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: sqlcl-pvc
        - name: scripts
          configMap:
            defaultMode: 420
            name: sqlplus-scripts-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlcl-pvc
  namespace: 23aidemo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
