apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: instantclient
    app.kubernetes.io/name: sqlcl-liquibase
  name: instantclient-sqlcl-liquibase
  namespace: 23aidemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: instantclient
      app.kubernetes.io/name: sqlcl-liquibase
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: instantclient
        app.kubernetes.io/name: sqlcl-liquibase
    spec:
      containers:
      - name: app
        env:
        - name: ORAPWD
          value: orapwd
        image: docker.io/ilfur/sqlcl-liquibase:21.3.0.0.0
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
          name: console
          protocol: TCP
        volumeMounts:
        - mountPath: /projects
          name: storage
      initContainers:
      - name: getFiles
        command:
          - /bin/bash
          - /scripts/getfiles.sh
        image: 'docker.io/ilfur/sqlcl-liquibase:21.3.0.0.0'
        imagePullPolicy: IfNotPresent
        name: getfiles
        volumeMounts:
          - mountPath: /scripts
            name: scripts
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: sqlcl-pvc
        - name: scripts
          configMap:
            defaultMode: 420
            name: sqlplus-scripts-config
