apiVersion: v1
kind: Service
metadata:
  labels:
    app: cdbtest-app
  name: cdbtest-service
  namespace: oracle-database-operator-system
spec:
  ports:
  - name: tcp-cmpdemoapp-container-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cdbtest-app
  sessionAffinity: None
  type: LoadBalancer
