apiVersion: v1
kind: Service
metadata:
  labels:
    app: cdbtest-app
  name: cdbtest-service
  namespace: oracle-database-operator-system
spec:
  ports:
  - name: tcp-cmpdemoapp-container-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cdbtest-app
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cdbtest-vservice
  namespace: oracle-database-operator-system
spec:
  gateways:
  - istio-system/http-istio-gateway
  hosts:
  - 'testapp.141.147.33.9.nip.io'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: cdbtest-service
        port:
          number: 8080

