apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: pythonflask-appconf
  namespace: oracle-database-operator-system
  annotations:
    description: "python flask app config"
spec:
      components:
        - componentName: vz-flask-comp
          traits:
            - trait:
                apiVersion: oam.verrazzano.io/v1alpha1
                kind: MetricsTrait
                spec:
                  scraper: verrazzano-system/vmi-system-prometheus-0
                  port: 5000
                  path: "/metrics"
            - trait:
                apiVersion: oam.verrazzano.io/v1alpha1
                kind: IngressTrait
                metadata:
                  name: pythonflask-ingress
                spec:
                  rules:
                    - paths:
                        - path: "/"
                          pathType: Prefix
            - trait:                      
                apiVersion: core.oam.dev/v1alpha2
                kind: ManualScalerTrait
                spec:
                  replicaCount: 3


