apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: vz-flask-comp
  namespace: oracle-database-operator-system
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: pythonflask
      namespace: python
      labels:
        app: pythonflask
        version: v1
    spec:
      containers:
        - name: app
          image: ilfur/pythonflask:1.0
          ports:
            - containerPort: 5000
              name: pythonflask
          imagePullPolicy: Always
