-- Create Tablespace
CREATE TABLESPACE tbsvec
DATAFILE '/opt/oracle/oradata/FREE/aipdb/tbsvec.dbf' SIZE 5G AUTOEXTEND ON
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
-- Create User "vector"
DROP USER vector CASCADE;
CREATE USER vector IDENTIFIED BY vector DEFAULT TABLESPACE tbsvec
QUOTA UNLIMITED ON tbsvec;
GRANT DB_DEVELOPER_ROLE TO vector;
GRANT CREATE MINING MODEL TO vector;
GRANT CREATE ANY CREDENTIAL TO vector;
CREATE OR REPLACE DIRECTORY vec_dump AS '/opt/vecdump';
GRANT READ, WRITE ON DIRECTORY vec_dump TO vector;
